name: jazone_1
description: "JAzone Flutter App (Citizen + Responder)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.1.1
  firebase_app_check: ^0.4.1+3
  firebase_messaging: ^16.0.0

  # Media + location + maps
  image_picker: ^1.2.1
  camera: ^0.11.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.6.1

  # Storage (keep Supabase – do not remove)
  supabase_flutter: ^2.5.0

  # Local persistence
  shared_preferences: ^2.2.3

  # env
  flutter_dotenv: ^5.1.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/preb.png
    - assets/logo.png
    - assets/tips.png
    - .env
